services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: eduard_sandor
      POSTGRES_PASSWORD: IONCuvaca2025
      POSTGRES_DB: eduard_sandor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python backend/run.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: backend/run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://eduard_sandor:IONCuvaca2025@db/eduard_sandor_db

volumes:
  postgres_data:
